
CREATE DATABASE IF NOT EXISTS todoapp
DEFAULT CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci;


USE todoapp;


CREATE TABLE IF NOT EXISTS crud (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    completed TINYINT(1) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
